version: "3"
services:

  teslalogger:
    build: docker/teslalogger/.
    restart: always
    volumes:
      - ./TeslaLogger/bin:/etc/teslalogger
      - ./Teslalogger/Grafana/:/var/lib/grafana/dashboards/
      - ./Teslalogger/GrafanaPlugins/:/var/lib/grafana/plugins
    depends_on:
      - database
  
  database:
    image: mariadb:10.4.7
    restart: always
    env_file:
      - .env
    volumes:
      - ./TeslaLogger/sqlschema.sql:/docker-entrypoint-initdb.d/sqlschema.sql
    ports: 
      - 3306:3306
        
  grafana:
    image: grafana/grafana:6.3.2
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=teslalogger
    ports: 
      - 3000:3000
    volumes: 
      - ./TeslaLogger/bin:/etc/teslalogger
      - ./Teslalogger/Grafana/:/var/lib/grafana/dashboards/
      - ./Teslalogger/GrafanaPlugins/:/var/lib/grafana/plugins
      - ./Teslalogger/GrafanaConfig/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./Teslalogger/GrafanaConfig/sample.yaml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - teslalogger-grafana:/var/lib/grafana
    depends_on:
      - database

  webserver:
    image: php:7.3-apache
    restart: always
    volumes:
      - ./TeslaLogger/www:/var/www/html
      - ./TeslaLogger/bin:/etc/teslalogger
      - ./TeslaLogger/Properties/AssemblyInfo.cs:/etc/teslalogger/git/TeslaLogger/Properties/AssemblyInfo.cs
    ports:
      - 8888:80
            
volumes:
    teslalogger-grafana: