version: "3"
services:
  teslalogger:
    build: .
    volumes:
      - teslalogger-bin:/etc/teslalogger
  
  sql:
    image: mariadb:10.4.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=teslalogger
      - MYSQL_USER=root
      - MYSQL_PASSWORD=teslalogger
    domainname: teslalogger
    hostname: teslalogger-sql
    volumes:
      - teslalogger-mariadb:/var/lib/mysql
  grafana:
    image: grafana/grafana:6.3.2
    environment:
      - DATABASE_USER=teslalogger
      - DATABASE_PASS=teslalogger
      - DATABASE_NAME=admin
      - DATABASE_HOST=db
    domainname: teslalogger
    hostname: teslalogger-grafana
    ports: 
      - 3000:3000
    volumes: 
      - teslalogger-grafana-data:/var/lib/grafana

volumes:
    teslalogger-grafana-data:
    teslalogger-mariadb:
    teslalogger-bin: